### ISSUE TITLE
macOS iterm2 won't display proper color codes in zsh / bash

### ISSUE THREAD

**Issue by solus-hq** [hakerdefo/pmrp#2]
<img width="331" alt="screen shot 2017-03-19 at 18 21 37" src="https://cloud.githubusercontent.com/assets/26515805/24082093/0d521556-0cd1-11e7-9888-56a3cd42dbe1.png">

Any help is greatly appreciated!

**Comment by hakerdefo** [comment]
Hi there @tallinn-code,
You'll need to upgrade bash on your Mac OS system. Apple, due to licensing problems ships an outdated version of bash on Mac OS. You can very easily upgrade bash on Mac OS. Here is a nice tutorial that will help you upgrade bash,

[Upgrade to bash 4 in Mac OS](http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/)

Cheers!!!

**Comment by solus-hq** [comment]
Thank you for support! Now it's working, brew installation of bash v.4 went just fine.

**Comment by hakerdefo** [comment]
Great!!!

Cheers!!!
